/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Stateful notification manager.
 *
 * ```js
 * const { Apprise } = require('apprise');
 * const a = new Apprise();
 * a.add('ntfy://mytopic');
 * a.add('slack://TokenA/TokenB/TokenC');
 * await a.notify('Hello!', { title: 'Test' });
 * ```
 */
export declare class Apprise {
  /** Create a new Apprise instance. */
  constructor()
  /** Add a notification service by URL. Returns true if parsed successfully. */
  add(url: string): boolean
  /** Load services from a config file (synchronous — blocks until loaded). */
  addConfig(path: string): number
  /** Get the number of loaded services. */
  len(): number
  /** Check if no services are loaded. */
  isEmpty(): boolean
  /** Send a notification to all loaded services. */
  notify(body: string, options?: NotifyOptions | undefined | null): Promise<SendResult>
  /** Get details of all loaded services. */
  details(): Array<ServiceInfo>
  /** Clear all loaded services. */
  clear(): void
}
export type JsApprise = Apprise

/** List all supported notification services. */
export declare function listServices(): Array<ServiceInfo>

/** Options for the notify method on the Apprise class. */
export interface NotifyOptions {
  title?: string
  notificationType?: string
  bodyFormat?: string
  tag?: string
}

/** Parse a notification URL and return service info, or null if invalid. */
export declare function parseUrl(url: string): ServiceInfo | null

/**
 * Send a one-shot notification. Creates an Apprise instance, adds URLs/config,
 * and sends the notification.
 */
export declare function send(options: SendOptions): Promise<SendResult>

/** Options for sending a notification. */
export interface SendOptions {
  /** Notification service URL(s), separated by commas or semicolons. */
  urls?: string
  /** Path to a configuration file. */
  config?: string
  /** Message body (required). */
  body: string
  /** Message title (optional). */
  title?: string
  /** Notification type: "info", "success", "warning", "failure". */
  notificationType?: string
  /** Body format: "text", "html", "markdown". */
  bodyFormat?: string
  /** Tag filter(s) — comma-separated AND groups. */
  tag?: string
}

/** Result of a notification dispatch. */
export interface SendResult {
  /** Total number of services targeted. */
  total: number
  /** Number that succeeded. */
  succeeded: number
  /** Number that failed. */
  failed: number
}

/** Information about a notification service. */
export interface ServiceInfo {
  /** Human-readable service name. */
  name: string
  /** URL scheme(s) (e.g., ["ntfy", "ntfys"]). */
  protocols: Array<string>
  /** Short description. */
  description: string
  /** Whether the service supports file attachments. */
  attachmentSupport: boolean
}
