services:
  apprise:
    build: .
    environment:
      - APPRISE_URLS
      - APPRISE_CONFIG_PATH
      - APPRISE_BODY
      - APPRISE_STORAGE_PATH=/data/cache
    volumes:
      - apprise-data:/data

volumes:
  apprise-data:
